name: 'ARMv7 action'
description: 'Running environment for armv7 platform'
inputs:
  bin-folder:  
    description: 'Binary folder with tests'
    required: true
    default: 'build'
outputs:
  test-log: 
    description: 'path to test log'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bin-folder }}
  