name: ARMv7

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ ** ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: armv7 run
    steps:
      - name: armv7 action step
        id: test
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --file ./Dockerfile
