name: ARMv7

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: armv7 run
    steps:
      - name: armv7 action step
        id: test
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Run the private action
        uses: ./
